"""add periods and schedule slots

Revision ID: 47199d373232
Revises: eb6fa30adf6e
Create Date: 2026-09-03 23:36:16.958314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47199d373232'
down_revision: Union[str, Sequence[str], None] = 'eb6fa30adf6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('periods',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('end_time > start_time', name='ck_periods_end_after_start'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_periods_name')
    )
    op.create_table('schedule_slots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('class_id', sa.UUID(), nullable=False),
    sa.Column('period_id', sa.UUID(), nullable=False),
    sa.Column('day_of_week', sa.Enum('monday', 'tuesday', 'wednesday', 'thursday', 'friday', name='day_of_week'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['period_id'], ['periods.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('class_id', 'day_of_week', 'period_id', name='uq_schedule_slots_class_day_period')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('schedule_slots')
    op.drop_table('periods')
    # ### end Alembic commands ###
    # A Postgres named enum type outlives the table that used it, so
    # without this a downgrade-then-upgrade fails with "type day_of_week
    # already exists". Autogenerate never emits it. The codebase's earlier
    # enum migrations have the same gap; left alone there rather than
    # retro-fitting migrations whose downgrades have never been run.
    op.execute("DROP TYPE IF EXISTS day_of_week")
