"""add student pin, profile pictures, student number sequence

Revision ID: 5c135e0f47fd
Revises: 9626ce1fafaf
Create Date: 2026-08-21 13:54:25.017831

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c135e0f47fd'
down_revision: Union[str, Sequence[str], None] = '9626ce1fafaf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE SEQUENCE student_number_seq START WITH 1")
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('pin_hash', sa.String(), nullable=True))
    op.add_column('students', sa.Column('profile_picture_path', sa.String(), nullable=True))
    op.add_column('teachers', sa.Column('profile_picture_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teachers', 'profile_picture_path')
    op.drop_column('students', 'profile_picture_path')
    op.drop_column('students', 'pin_hash')
    # ### end Alembic commands ###
    op.execute("DROP SEQUENCE student_number_seq")
