"""add super_admin role and audit_logs table

Revision ID: 666f7c30cf84
Revises: d3033f1c17ad
Create Date: 2026-08-19 23:17:31.450072

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '666f7c30cf84'
down_revision: Union[str, Sequence[str], None] = 'd3033f1c17ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Alembic's autogenerate does not detect additions to an existing
    # Postgres native ENUM type — added by hand. Safe inside a transaction
    # on Postgres 12+ as long as the new value isn't used in this same
    # transaction (it isn't).
    op.execute("ALTER TYPE user_role ADD VALUE 'super_admin'")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('actor_user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('target_user_id', sa.UUID(), nullable=True),
    sa.Column('before', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['target_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # Deliberately not reverting the enum value: Postgres has no
    # `ALTER TYPE ... DROP VALUE`. Removing one requires renaming the type,
    # creating a replacement without the value, migrating every column
    # over, then dropping the old type — real work, only worth doing if
    # this downgrade path is ever actually needed. Any 'super_admin' rows
    # would also need reassigning first, or this would fail regardless.
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
