"""add students table

Revision ID: 93f60331390d
Revises: d350b1306a85
Create Date: 2026-08-18 22:02:33.266456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93f60331390d'
down_revision: Union[str, Sequence[str], None] = 'd350b1306a85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('students',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('student_number', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('enrollment_status', sa.Enum('active', 'inactive', 'graduated', 'withdrawn', name='student_enrollment_status'), nullable=False),
    sa.Column('guardian_name', sa.String(), nullable=False),
    sa.Column('guardian_phone', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('date_of_birth <= CURRENT_DATE', name='ck_students_dob_not_future'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', name='uq_students_email'),
    sa.UniqueConstraint('student_number', name='uq_students_student_number')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('students')
    # ### end Alembic commands ###
