"""add grade levels, sections, section assignments

Revision ID: eb6fa30adf6e
Revises: 5c135e0f47fd
Create Date: 2026-09-03 22:11:30.090974

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb6fa30adf6e'
down_revision: Union[str, Sequence[str], None] = '5c135e0f47fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grade_levels',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('rank >= 0', name='ck_grade_levels_rank_non_negative'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_grade_levels_name'),
    sa.UniqueConstraint('rank', name='uq_grade_levels_rank')
    )
    op.create_table('sections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('grade_level_id', sa.UUID(), nullable=False),
    sa.Column('academic_year_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('class_teacher_id', sa.UUID(), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('capacity > 0', name='ck_sections_capacity_positive'),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_years.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['class_teacher_id'], ['teachers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['grade_level_id'], ['grade_levels.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('grade_level_id', 'academic_year_id', 'name', name='uq_sections_grade_year_name')
    )
    op.create_table('section_assignments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('section_id', sa.UUID(), nullable=False),
    sa.Column('academic_year_id', sa.UUID(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_years.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'academic_year_id', name='uq_section_assignments_student_year')
    )
    op.add_column('classes', sa.Column('section_id', sa.UUID(), nullable=True))
    # Named explicitly — autogenerate emits None here, which makes the
    # downgrade's drop_constraint(None, ...) unrunnable.
    op.create_foreign_key(
        'fk_classes_section_id', 'classes', 'sections', ['section_id'], ['id'],
        ondelete='RESTRICT',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_classes_section_id', 'classes', type_='foreignkey')
    op.drop_column('classes', 'section_id')
    op.drop_table('section_assignments')
    op.drop_table('sections')
    op.drop_table('grade_levels')
    # ### end Alembic commands ###
